[monolith]
instance_name = "monoloth_standard"
log_file_name = "monolith"
registration_db_path = "/tmp/monolith_registration.db"
metric_db_path = "/tmp/monolith_metrics.db"

[networking]
use_ipv6 = false
ipv4_address = "0.0.0.0"
ipv6_address = "::1"
http_port = 8080
metric_submission_port = 9000

[rules]
rule_script = "rules/default.lua"

[alert]
max_alert_sends = 0                # 0 = infinite
alert_cooldown_seconds = 40.0      # Seconds to cool down per alert id

[twilio]
account_sid = ""
auth_token = ""
from = ""
to = ""