[monolith]
instance_name = "monoloth_standard"
log_file_name = "monolith"
registration_db_path = "/tmp/monolith_registration.db"
rule_script = "rules/default.lua"

[networking]
ipv4_address = "0.0.0.0"
http_port = 8080
telnet_enabled = true
telnet_port = 25565
telnet_access_code = "password123"

[metrics]
save_metrics = true
path = "/tmp/monolith_metrics.db"
metric_expiration_time_sec = 604800 # 0 = infinite
enable_metric_streamer = true

[alerts]
max_alert_sends = 0                # 0 = infinite
alert_cooldown_seconds = 40.0      # Seconds to cool down per alert id

#  Optional setup for sms backend

# [twilio]
# account_sid = ""
# auth_token = ""
# from = ""
# to = []