[monolith]
instance_name = "pycrate_standard"
log_file_name = "pycrate"
registration_db_path = "/tmp/pycrate_registration.db"
rule_script = "rules/pycrate.lua"

[networking]
ipv4_address = "0.0.0.0"
http_port = 8080
telnet_enabled = false
telnet_port = 25565
telnet_access_code = ""

[metrics]
save_metrics = true
path = "/tmp/pycrate_metrics.db"
metric_expiration_time_sec = 604800 # 0 = infinite
enable_metric_streamer = true

[alert]
max_alert_sends = 0                # 0 = infinite
alert_cooldown_seconds = 40.0      # Seconds to cool down per alert id
